#  settings

# mandatory
url = "..url"
keyStorePath = "path/...moc.json"
passwordFrom = "password"
addressTo = "0x.."

# defaults
maxRounds = 3
gasPrice = "1000000000"
simpleTransactionGas = "21000"
amountToSend = "20000000000"
consensensusAbiPath = "./contracts/PoaNetworkConsensus.abi.json"
contractsAddressPath = "./contracts/contracts.json"
timeoutSeconds = 15
